// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TimeTrackerNet.Models;

public partial class ProgressTrackerContext : DbContext
{
    public ProgressTrackerContext()
    {
    }

    public ProgressTrackerContext(DbContextOptions<ProgressTrackerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TimeTracking> TimeTracking { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)

        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-K9UQT61;Initial Catalog=ProgressTracker;Integrated Security=True;TrustServerCertificate=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TimeTracking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TimeTrac__3214EC07A3DE9063");

            entity.Property(e => e.Category)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Date).HasColumnType("date");
            entity.Property(e => e.Skill)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}